### ISSUE TITLE
Confusing error message "Unhandled promise rejection"

### ISSUE THREAD

**Issue by aakoch** [zachleat/eleventy#7]
I'm not sure you can do anything about this, but if I have some incorrect Pug syntax, I get an error like this:
```
File changed: index.pug
(node:17395) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 2): Error: Pug:4:17
    2| html(lang="en")
    3|   head
  > 4|     title= Some Title
-----------------------^
    5|   body
    6|     h1= title
    7|     p Source available at

Syntax Error: Unexpected token
(node:17395) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```
Now, the "Error: Pug:4:17" and "Syntax Error: Unexpected token" is correct. The "confusing" part is the "UnhandledPromiseRejectionWarning" and the "DeprecationWarning". 

This is the error I get if I use the pug command:
```
> pug . --output _site

~/.npm-packages/lib/node_modules/pug-cli/node_modules/pug-lexer/index.js:59
    throw err;
    ^

Error: ./index.pug:7:17
    5| html(lang="en")
    6|   head
  > 7|     title= Some Title
-----------------------^
    8|   body
    9|     h1= title
    10|     p Source available at

Syntax Error: Unexpected token
    at makeError (~/.npm-packages/lib/node_modules/pug-cli/node_modules/pug-error/index.js:32:13)
    at Lexer.error (~/.npm-packages/lib/node_modules/pug-cli/node_modules/pug-lexer/index.js:58:15)
    at Lexer.assertExpression (~/.npm-packages/lib/node_modules/pug-cli/node_modules/pug-lexer/index.js:86:12)
    at Lexer.code (~/.npm-packages/lib/node_modules/pug-cli/node_modules/pug-lexer/index.js:971:28)
    at Lexer.callLexerFunction (~/.npm-packages/lib/node_modules/pug-cli/node_modules/pug-lexer/index.js:1319:23)
    at Lexer.advance (~/.npm-packages/lib/node_modules/pug-cli/node_modules/pug-lexer/index.js:1352:15)
    at Lexer.callLexerFunction (~/.npm-packages/lib/node_modules/pug-cli/node_modules/pug-lexer/index.js:1319:23)
    at Lexer.getTokens (~/.npm-packages/lib/node_modules/pug-cli/node_modules/pug-lexer/index.js:1375:12)
    at lex (~/.npm-packages/lib/node_modules/pug-cli/node_modules/pug-lexer/index.js:12:42)
    at Object.lex (~/.npm-packages/lib/node_modules/pug-cli/node_modules/pug/lib/index.js:99:27)
```

**Comment by zachleat** [comment]
Put some work into improving this for v0.1.4 (releasing soon).

![image](https://user-images.githubusercontent.com/39355/34359724-08c3cce6-ea20-11e7-86a2-548b2a01cd1b.png)
