### ISSUE TITLE
When using .eleventy.js with input.dir – Error: The "path" argument must be of type string

### ISSUE THREAD

**Issue by kleinfreund** [zachleat/eleventy#8]
```
> eleventy --version
0.1.5
```

**Steps to reproduce:**

1. Create the directoy `./src`, within it, create a `index.html` file.
2. Run `eleventy`. A file will be written to `./_site/src/index.html`. No errors.
3. Create `.eleventy.js` as follows:

   ```js
   module.exports = {
     dir: {
       input: 'src'
     }
   };
   ```

4. Run `elventy`.

**Expected behavior:**

`eleventy` runs without failure.

**Actual behavior:**

The following error is shown. As far as I can tell, every `eleventy` command produces that error.

```
(node:21055) UnhandledPromiseRejectionWarning: TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string
    at assertPath (path.js:28:11)
    at Object.join (path.js:1244:7)
    at Function.TemplatePath.normalize (/home/phil/.npm-global/lib/node_modules/eleventy-cli/src/TemplatePath.js:16:25)
    at TemplateData.getGlobalDataGlob (/home/phil/.npm-global/lib/node_modules/eleventy-cli/src/TemplateData.js:48:23)
    at <anonymous>
(node:21055) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:21055) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by zachleat** [comment]
Confirmed and fixed! This will be included with 0.1.6 (added a test for this too)
